# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/ui_XML/addAuthor_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(890, 730)
        Form.setStyleSheet("QLabel#addAuthor_label {\n"
"    background-color: green;\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 781, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addAuthor_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.addAuthor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.addAuthor_label.setObjectName("addAuthor_label")
        self.horizontalLayout.addWidget(self.addAuthor_label)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(160, 130, 571, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.authorName_label = QtWidgets.QLabel(self.frame)
        self.authorName_label.setGeometry(QtCore.QRect(10, 30, 58, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.authorName_label.setFont(font)
        self.authorName_label.setObjectName("authorName_label")
        self.authorName_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.authorName_lineEdit.setGeometry(QtCore.QRect(110, 30, 271, 35))
        self.authorName_lineEdit.setObjectName("authorName_lineEdit")
        self.authorSurname_label = QtWidgets.QLabel(self.frame)
        self.authorSurname_label.setGeometry(QtCore.QRect(10, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.authorSurname_label.setFont(font)
        self.authorSurname_label.setObjectName("authorSurname_label")
        self.authorSurname_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.authorSurname_lineEdit.setGeometry(QtCore.QRect(110, 80, 271, 35))
        self.authorSurname_lineEdit.setObjectName("authorSurname_lineEdit")
        self.addAuthor_button = QtWidgets.QPushButton(self.frame)
        self.addAuthor_button.setGeometry(QtCore.QRect(110, 140, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addAuthor_button.setFont(font)
        self.addAuthor_button.setObjectName("addAuthor_button")
        self.clearAll_button = QtWidgets.QPushButton(self.frame)
        self.clearAll_button.setGeometry(QtCore.QRect(250, 140, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearAll_button.setFont(font)
        self.clearAll_button.setObjectName("clearAll_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addAuthor_label.setText(_translate("Form", "Add Author"))
        self.authorName_label.setText(_translate("Form", "Name:"))
        self.authorSurname_label.setText(_translate("Form", "Surname:"))
        self.addAuthor_button.setText(_translate("Form", "Add author"))
        self.clearAll_button.setText(_translate("Form", "Clear all"))
