# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/ui_XML/addBook_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(890, 730)
        Form.setStyleSheet("QLabel#addBook_label {\n"
"    background-color:  green;\n"
"}")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(150, 130, 581, 391))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.bookTitle_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookTitle_label.setObjectName("bookTitle_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bookTitle_label)
        self.bookTitle_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookTitle_lineEdit.setObjectName("bookTitle_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bookTitle_lineEdit)
        self.ISBN_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.ISBN_label.setObjectName("ISBN_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ISBN_label)
        self.ISBN_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ISBN_lineEdit.setObjectName("ISBN_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ISBN_lineEdit)
        self.author_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.author_label.setObjectName("author_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.author_label)
        self.author_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.author_comboBox.setObjectName("author_comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.author_comboBox)
        self.category_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.category_label.setObjectName("category_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.category_label)
        self.category_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.category_comboBox.setObjectName("category_comboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.category_comboBox)
        self.cover_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.cover_label.setObjectName("cover_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.cover_label)
        self.uploadCover_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.uploadCover_button.setObjectName("uploadCover_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.uploadCover_button)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label)
        self.description_plainText = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.description_plainText.setObjectName("description_plainText")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.description_plainText)
        self.image_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.image_label)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(49, 29, 781, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBook_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.addBook_label.setAlignment(QtCore.Qt.AlignCenter)
        self.addBook_label.setIndent(-1)
        self.addBook_label.setObjectName("addBook_label")
        self.horizontalLayout.addWidget(self.addBook_label)
        self.addBook_button = QtWidgets.QPushButton(Form)
        self.addBook_button.setGeometry(QtCore.QRect(150, 560, 80, 31))
        self.addBook_button.setObjectName("addBook_button")
        self.clearAll_button = QtWidgets.QPushButton(Form)
        self.clearAll_button.setGeometry(QtCore.QRect(270, 560, 80, 31))
        self.clearAll_button.setObjectName("clearAll_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bookTitle_label.setText(_translate("Form", "Book title"))
        self.ISBN_label.setText(_translate("Form", "ISBN"))
        self.author_label.setText(_translate("Form", "Author"))
        self.category_label.setText(_translate("Form", "Category"))
        self.cover_label.setText(_translate("Form", "Cover"))
        self.uploadCover_button.setText(_translate("Form", "Upload cover"))
        self.label.setText(_translate("Form", "Description"))
        self.addBook_label.setText(_translate("Form", "Add book"))
        self.addBook_button.setText(_translate("Form", "Add book"))
        self.clearAll_button.setText(_translate("Form", " Clear all"))
