# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/ui_XML/addCategory_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(890, 730)
        Form.setStyleSheet("QLabel#addCategory_label {\n"
"    background-color: green;\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 781, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addCategory_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.addCategory_label.setAlignment(QtCore.Qt.AlignCenter)
        self.addCategory_label.setObjectName("addCategory_label")
        self.horizontalLayout.addWidget(self.addCategory_label)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(150, 120, 581, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.categoryName_label = QtWidgets.QLabel(self.frame)
        self.categoryName_label.setGeometry(QtCore.QRect(70, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.categoryName_label.setFont(font)
        self.categoryName_label.setObjectName("categoryName_label")
        self.categoryName_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.categoryName_lineEdit.setGeometry(QtCore.QRect(140, 30, 371, 40))
        self.categoryName_lineEdit.setObjectName("categoryName_lineEdit")
        self.addCategory_button = QtWidgets.QPushButton(self.frame)
        self.addCategory_button.setGeometry(QtCore.QRect(140, 90, 371, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addCategory_button.setFont(font)
        self.addCategory_button.setObjectName("addCategory_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addCategory_label.setText(_translate("Form", "Add category"))
        self.categoryName_label.setText(_translate("Form", "Name:"))
        self.addCategory_button.setText(_translate("Form", "Add category"))
