# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/ui_XML/coverIllustration_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        self.coverIllustration_label = QtWidgets.QLabel(Dialog)
        self.coverIllustration_label.setGeometry(QtCore.QRect(0, 0, 400, 500))
        self.coverIllustration_label.setText("")
        self.coverIllustration_label.setObjectName("coverIllustration_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
