# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/ui_XML/homepage_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(890, 730)
        Form.setStyleSheet("QLabel#homepage_label {\n"
"    background-color: green;\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 781, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.homepage_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.homepage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.homepage_label.setObjectName("homepage_label")
        self.horizontalLayout.addWidget(self.homepage_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.homepage_label.setText(_translate("Form", "Homepage"))
