# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_management_system/assets/XML/addGenre_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addGenre_window(object):
    def setupUi(self, addGenre_window):
        addGenre_window.setObjectName("addGenre_window")
        addGenre_window.resize(890, 730)
        self.formLayout = QtWidgets.QFormLayout(addGenre_window)
        self.formLayout.setObjectName("formLayout")
        self.addGenre_label = QtWidgets.QLabel(addGenre_window)
        self.addGenre_label.setAlignment(QtCore.Qt.AlignCenter)
        self.addGenre_label.setObjectName("addGenre_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.addGenre_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.genreName_label = QtWidgets.QLabel(addGenre_window)
        self.genreName_label.setObjectName("genreName_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.genreName_label)
        self.genreName_lineEdit = QtWidgets.QLineEdit(addGenre_window)
        self.genreName_lineEdit.setObjectName("genreName_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.genreName_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.addGenre_button = QtWidgets.QPushButton(addGenre_window)
        self.addGenre_button.setObjectName("addGenre_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.addGenre_button)

        self.retranslateUi(addGenre_window)
        QtCore.QMetaObject.connectSlotsByName(addGenre_window)

    def retranslateUi(self, addGenre_window):
        _translate = QtCore.QCoreApplication.translate
        addGenre_window.setWindowTitle(_translate("addGenre_window", "Form"))
        self.addGenre_label.setText(_translate("addGenre_window", "Add genre"))
        self.genreName_label.setText(_translate("addGenre_window", "Name:"))
        self.addGenre_button.setText(_translate("addGenre_window", "Add genre"))
