# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_management_system/assets/XML/allFilmDirectors_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AllFilmDirectors_window(object):
    def setupUi(self, AllFilmDirectors_window):
        AllFilmDirectors_window.setObjectName("AllFilmDirectors_window")
        AllFilmDirectors_window.resize(890, 730)
        self.verticalLayout = QtWidgets.QVBoxLayout(AllFilmDirectors_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.allFilmDirectors_label = QtWidgets.QLabel(AllFilmDirectors_window)
        self.allFilmDirectors_label.setAlignment(QtCore.Qt.AlignCenter)
        self.allFilmDirectors_label.setObjectName("allFilmDirectors_label")
        self.verticalLayout.addWidget(self.allFilmDirectors_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.searchFilmDirector_lineEdit = QtWidgets.QLineEdit(AllFilmDirectors_window)
        self.searchFilmDirector_lineEdit.setObjectName("searchFilmDirector_lineEdit")
        self.verticalLayout.addWidget(self.searchFilmDirector_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.allFilmDirectors_tableView = QtWidgets.QTableView(AllFilmDirectors_window)
        self.allFilmDirectors_tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.allFilmDirectors_tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.allFilmDirectors_tableView.setObjectName("allFilmDirectors_tableView")
        self.verticalLayout.addWidget(self.allFilmDirectors_tableView)

        self.retranslateUi(AllFilmDirectors_window)
        QtCore.QMetaObject.connectSlotsByName(AllFilmDirectors_window)

    def retranslateUi(self, AllFilmDirectors_window):
        _translate = QtCore.QCoreApplication.translate
        AllFilmDirectors_window.setWindowTitle(_translate("AllFilmDirectors_window", "Form"))
        self.allFilmDirectors_label.setText(_translate("AllFilmDirectors_window", "All film directors"))
