# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_management_system/assets/XML/filmDirector_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filmDirector_window(object):
    def setupUi(self, filmDirector_window):
        filmDirector_window.setObjectName("filmDirector_window")
        filmDirector_window.resize(890, 730)
        self.verticalLayout = QtWidgets.QVBoxLayout(filmDirector_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(filmDirector_window)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.filmDirectorName_label = QtWidgets.QLabel(self.tab)
        self.filmDirectorName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.filmDirectorName_label.setObjectName("filmDirectorName_label")
        self.gridLayout.addWidget(self.filmDirectorName_label, 0, 0, 1, 1)
        self.filmDirectorSurname_label = QtWidgets.QLabel(self.tab)
        self.filmDirectorSurname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.filmDirectorSurname_label.setObjectName("filmDirectorSurname_label")
        self.gridLayout.addWidget(self.filmDirectorSurname_label, 1, 0, 1, 1)
        self.filmDirectorWikipedia_label = QtWidgets.QLabel(self.tab)
        self.filmDirectorWikipedia_label.setAlignment(QtCore.Qt.AlignCenter)
        self.filmDirectorWikipedia_label.setObjectName("filmDirectorWikipedia_label")
        self.gridLayout.addWidget(self.filmDirectorWikipedia_label, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout.setObjectName("formLayout")
        self.editFilmDirector_label = QtWidgets.QLabel(self.tab_2)
        self.editFilmDirector_label.setAlignment(QtCore.Qt.AlignCenter)
        self.editFilmDirector_label.setObjectName("editFilmDirector_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.editFilmDirector_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.filmDirectorName_label_2 = QtWidgets.QLabel(self.tab_2)
        self.filmDirectorName_label_2.setObjectName("filmDirectorName_label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.filmDirectorName_label_2)
        self.filmDirectorName_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.filmDirectorName_lineEdit.setObjectName("filmDirectorName_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.filmDirectorName_lineEdit)
        self.filmDirectorSurname_label_2 = QtWidgets.QLabel(self.tab_2)
        self.filmDirectorSurname_label_2.setObjectName("filmDirectorSurname_label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.filmDirectorSurname_label_2)
        self.filmDirectorSurname_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.filmDirectorSurname_lineEdit.setObjectName("filmDirectorSurname_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.filmDirectorSurname_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.editFilmDirector_button = QtWidgets.QPushButton(self.tab_2)
        self.editFilmDirector_button.setObjectName("editFilmDirector_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.editFilmDirector_button)
        self.deleteFilmDirector_button = QtWidgets.QPushButton(self.tab_2)
        self.deleteFilmDirector_button.setObjectName("deleteFilmDirector_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.deleteFilmDirector_button)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(filmDirector_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(filmDirector_window)

    def retranslateUi(self, filmDirector_window):
        _translate = QtCore.QCoreApplication.translate
        filmDirector_window.setWindowTitle(_translate("filmDirector_window", "Form"))
        self.filmDirectorName_label.setText(_translate("filmDirector_window", "Name"))
        self.filmDirectorSurname_label.setText(_translate("filmDirector_window", "Surname"))
        self.filmDirectorWikipedia_label.setText(_translate("filmDirector_window", "Wikipedia"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("filmDirector_window", "Details"))
        self.editFilmDirector_label.setText(_translate("filmDirector_window", "Edit film director"))
        self.filmDirectorName_label_2.setText(_translate("filmDirector_window", "Name:"))
        self.filmDirectorSurname_label_2.setText(_translate("filmDirector_window", "Surname:"))
        self.editFilmDirector_button.setText(_translate("filmDirector_window", "Edit film director"))
        self.deleteFilmDirector_button.setText(_translate("filmDirector_window", "Delete film director"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("filmDirector_window", "Edit/Delete"))
