# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_management_system/assets/XML/genre_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_genre_window(object):
    def setupUi(self, genre_window):
        genre_window.setObjectName("genre_window")
        genre_window.resize(890, 730)
        self.formLayout = QtWidgets.QFormLayout(genre_window)
        self.formLayout.setObjectName("formLayout")
        self.editGenre_label = QtWidgets.QLabel(genre_window)
        self.editGenre_label.setAlignment(QtCore.Qt.AlignCenter)
        self.editGenre_label.setObjectName("editGenre_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.editGenre_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.genreName_label = QtWidgets.QLabel(genre_window)
        self.genreName_label.setObjectName("genreName_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.genreName_label)
        self.genreName_lineEdit = QtWidgets.QLineEdit(genre_window)
        self.genreName_lineEdit.setObjectName("genreName_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.genreName_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.editGenre_button = QtWidgets.QPushButton(genre_window)
        self.editGenre_button.setObjectName("editGenre_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.editGenre_button)
        self.deleteGenre_button = QtWidgets.QPushButton(genre_window)
        self.deleteGenre_button.setObjectName("deleteGenre_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.deleteGenre_button)

        self.retranslateUi(genre_window)
        QtCore.QMetaObject.connectSlotsByName(genre_window)

    def retranslateUi(self, genre_window):
        _translate = QtCore.QCoreApplication.translate
        genre_window.setWindowTitle(_translate("genre_window", "Form"))
        self.editGenre_label.setText(_translate("genre_window", "Edit genre"))
        self.genreName_label.setText(_translate("genre_window", "Name:"))
        self.editGenre_button.setText(_translate("genre_window", "Edit genre"))
        self.deleteGenre_button.setText(_translate("genre_window", "Delete genre"))
