# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/XML/addAuthor_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addAuthor_window(object):
    def setupUi(self, addAuthor_window):
        addAuthor_window.setObjectName("addAuthor_window")
        addAuthor_window.resize(890, 730)
        self.formLayout = QtWidgets.QFormLayout(addAuthor_window)
        self.formLayout.setObjectName("formLayout")
        self.addAuthor_label = QtWidgets.QLabel(addAuthor_window)
        self.addAuthor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.addAuthor_label.setObjectName("addAuthor_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.addAuthor_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.authorName_label = QtWidgets.QLabel(addAuthor_window)
        self.authorName_label.setObjectName("authorName_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.authorName_label)
        self.authorName_lineEdit = QtWidgets.QLineEdit(addAuthor_window)
        self.authorName_lineEdit.setObjectName("authorName_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.authorName_lineEdit)
        self.authorSurname_label = QtWidgets.QLabel(addAuthor_window)
        self.authorSurname_label.setObjectName("authorSurname_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.authorSurname_label)
        self.authorSurname_lineEdit = QtWidgets.QLineEdit(addAuthor_window)
        self.authorSurname_lineEdit.setObjectName("authorSurname_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.authorSurname_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.addAuthor_button_1 = QtWidgets.QPushButton(addAuthor_window)
        self.addAuthor_button_1.setObjectName("addAuthor_button_1")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.addAuthor_button_1)
        self.clearAll_button = QtWidgets.QPushButton(addAuthor_window)
        self.clearAll_button.setObjectName("clearAll_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.clearAll_button)

        self.retranslateUi(addAuthor_window)
        QtCore.QMetaObject.connectSlotsByName(addAuthor_window)

    def retranslateUi(self, addAuthor_window):
        _translate = QtCore.QCoreApplication.translate
        addAuthor_window.setWindowTitle(_translate("addAuthor_window", "Form"))
        self.addAuthor_label.setText(_translate("addAuthor_window", "Add author"))
        self.authorName_label.setText(_translate("addAuthor_window", "Name:"))
        self.authorSurname_label.setText(_translate("addAuthor_window", "Surname:"))
        self.addAuthor_button_1.setText(_translate("addAuthor_window", "Add author"))
        self.clearAll_button.setText(_translate("addAuthor_window", "Clear all"))
