# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book_management_system/assets/XML/author_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_author_window(object):
    def setupUi(self, author_window):
        author_window.setObjectName("author_window")
        author_window.resize(890, 730)
        self.verticalLayout = QtWidgets.QVBoxLayout(author_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(author_window)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.authorWikipedia_label = QtWidgets.QLabel(self.tab)
        self.authorWikipedia_label.setAlignment(QtCore.Qt.AlignCenter)
        self.authorWikipedia_label.setOpenExternalLinks(True)
        self.authorWikipedia_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.authorWikipedia_label.setObjectName("authorWikipedia_label")
        self.gridLayout.addWidget(self.authorWikipedia_label, 2, 0, 1, 1)
        self.authorSurname_label = QtWidgets.QLabel(self.tab)
        self.authorSurname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.authorSurname_label.setObjectName("authorSurname_label")
        self.gridLayout.addWidget(self.authorSurname_label, 1, 0, 1, 1)
        self.authorName_label = QtWidgets.QLabel(self.tab)
        self.authorName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.authorName_label.setObjectName("authorName_label")
        self.gridLayout.addWidget(self.authorName_label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout.setObjectName("formLayout")
        self.editAuthor_label = QtWidgets.QLabel(self.tab_2)
        self.editAuthor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.editAuthor_label.setObjectName("editAuthor_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.editAuthor_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.authorName_label_2 = QtWidgets.QLabel(self.tab_2)
        self.authorName_label_2.setObjectName("authorName_label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.authorName_label_2)
        self.authorName_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.authorName_lineEdit.setObjectName("authorName_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.authorName_lineEdit)
        self.authorSurname_label_2 = QtWidgets.QLabel(self.tab_2)
        self.authorSurname_label_2.setObjectName("authorSurname_label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.authorSurname_label_2)
        self.authorSurname_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.authorSurname_lineEdit.setObjectName("authorSurname_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.authorSurname_lineEdit)
        self.editAuthor_button = QtWidgets.QPushButton(self.tab_2)
        self.editAuthor_button.setObjectName("editAuthor_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.editAuthor_button)
        self.deleteAuthor_button = QtWidgets.QPushButton(self.tab_2)
        self.deleteAuthor_button.setObjectName("deleteAuthor_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.deleteAuthor_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(author_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(author_window)

    def retranslateUi(self, author_window):
        _translate = QtCore.QCoreApplication.translate
        author_window.setWindowTitle(_translate("author_window", "Form"))
        self.authorWikipedia_label.setText(_translate("author_window", "Wikipedia"))
        self.authorSurname_label.setText(_translate("author_window", "Surname"))
        self.authorName_label.setText(_translate("author_window", "Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("author_window", "Details"))
        self.editAuthor_label.setText(_translate("author_window", "Edit author"))
        self.authorName_label_2.setText(_translate("author_window", "Name:"))
        self.authorSurname_label_2.setText(_translate("author_window", "Surname:"))
        self.editAuthor_button.setText(_translate("author_window", "Edit author"))
        self.deleteAuthor_button.setText(_translate("author_window", "Delete author"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("author_window", "Edit/Delete"))
