# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book_management_system/assets/XML/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1000, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(main_window)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_button = QtWidgets.QPushButton(main_window)
        self.home_button.setObjectName("home_button")
        self.verticalLayout.addWidget(self.home_button)
        self.addBook_button = QtWidgets.QPushButton(main_window)
        self.addBook_button.setObjectName("addBook_button")
        self.verticalLayout.addWidget(self.addBook_button)
        self.allBooks_button = QtWidgets.QPushButton(main_window)
        self.allBooks_button.setObjectName("allBooks_button")
        self.verticalLayout.addWidget(self.allBooks_button)
        self.addAuthor_button = QtWidgets.QPushButton(main_window)
        self.addAuthor_button.setObjectName("addAuthor_button")
        self.verticalLayout.addWidget(self.addAuthor_button)
        self.allAuthors_button = QtWidgets.QPushButton(main_window)
        self.allAuthors_button.setObjectName("allAuthors_button")
        self.verticalLayout.addWidget(self.allAuthors_button)
        self.addGenre_button = QtWidgets.QPushButton(main_window)
        self.addGenre_button.setObjectName("addGenre_button")
        self.verticalLayout.addWidget(self.addGenre_button)
        self.allGenres_button = QtWidgets.QPushButton(main_window)
        self.allGenres_button.setObjectName("allGenres_button")
        self.verticalLayout.addWidget(self.allGenres_button)
        self.statistics_button = QtWidgets.QPushButton(main_window)
        self.statistics_button.setObjectName("statistics_button")
        self.verticalLayout.addWidget(self.statistics_button)
        self.settings_button = QtWidgets.QPushButton(main_window)
        self.settings_button.setObjectName("settings_button")
        self.verticalLayout.addWidget(self.settings_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(main_window)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Form"))
        self.home_button.setText(_translate("main_window", "Home"))
        self.addBook_button.setText(_translate("main_window", "Add book"))
        self.allBooks_button.setText(_translate("main_window", "All books"))
        self.addAuthor_button.setText(_translate("main_window", "Add author"))
        self.allAuthors_button.setText(_translate("main_window", "All authors"))
        self.addGenre_button.setText(_translate("main_window", "Add genre"))
        self.allGenres_button.setText(_translate("main_window", "All genres"))
        self.statistics_button.setText(_translate("main_window", "Statistics"))
        self.settings_button.setText(_translate("main_window", "Settings"))
