# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/demoListWidgetOp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 500)
        font = QtGui.QFont()
        font.setPointSize(16)
        Dialog.setFont(font)
        self.itemLabel = QtWidgets.QLabel(Dialog)
        self.itemLabel.setGeometry(QtCore.QRect(10, 30, 141, 18))
        self.itemLabel.setObjectName("itemLabel")
        self.lineEditItem = QtWidgets.QLineEdit(Dialog)
        self.lineEditItem.setGeometry(QtCore.QRect(160, 20, 211, 26))
        self.lineEditItem.setObjectName("lineEditItem")
        self.pushButtonAddItem = QtWidgets.QPushButton(Dialog)
        self.pushButtonAddItem.setGeometry(QtCore.QRect(390, 20, 111, 30))
        self.pushButtonAddItem.setObjectName("pushButtonAddItem")
        self.listWidgetSelectedItems = QtWidgets.QListWidget(Dialog)
        self.listWidgetSelectedItems.setGeometry(QtCore.QRect(10, 80, 581, 251))
        self.listWidgetSelectedItems.setObjectName("listWidgetSelectedItems")
        self.pushButtonEditItem = QtWidgets.QPushButton(Dialog)
        self.pushButtonEditItem.setGeometry(QtCore.QRect(30, 360, 80, 30))
        self.pushButtonEditItem.setObjectName("pushButtonEditItem")
        self.pushButtonDeleteItem = QtWidgets.QPushButton(Dialog)
        self.pushButtonDeleteItem.setGeometry(QtCore.QRect(210, 360, 150, 30))
        self.pushButtonDeleteItem.setObjectName("pushButtonDeleteItem")
        self.pushButtonDeleteAll = QtWidgets.QPushButton(Dialog)
        self.pushButtonDeleteAll.setGeometry(QtCore.QRect(440, 360, 150, 30))
        self.pushButtonDeleteAll.setObjectName("pushButtonDeleteAll")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.itemLabel.setText(_translate("Dialog", "Enter an item:"))
        self.pushButtonAddItem.setText(_translate("Dialog", "Add item"))
        self.pushButtonEditItem.setText(_translate("Dialog", "Edit"))
        self.pushButtonDeleteItem.setText(_translate("Dialog", "Delete item"))
        self.pushButtonDeleteAll.setText(_translate("Dialog", "Delete all"))
