# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/demoCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 600)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 100, 191, 40))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 180, 221, 40))
        self.label_2.setObjectName("label_2")
        self.lineEditFirstNumber = QtWidgets.QLineEdit(Dialog)
        self.lineEditFirstNumber.setGeometry(QtCore.QRect(270, 110, 300, 26))
        self.lineEditFirstNumber.setObjectName("lineEditFirstNumber")
        self.lineEditSecondNumber = QtWidgets.QLineEdit(Dialog)
        self.lineEditSecondNumber.setGeometry(QtCore.QRect(280, 190, 300, 26))
        self.lineEditSecondNumber.setObjectName("lineEditSecondNumber")
        self.pushButtonAdd = QtWidgets.QPushButton(Dialog)
        self.pushButtonAdd.setGeometry(QtCore.QRect(20, 300, 100, 50))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonSub = QtWidgets.QPushButton(Dialog)
        self.pushButtonSub.setGeometry(QtCore.QRect(170, 300, 100, 50))
        self.pushButtonSub.setObjectName("pushButtonSub")
        self.pushButtonMul = QtWidgets.QPushButton(Dialog)
        self.pushButtonMul.setGeometry(QtCore.QRect(320, 300, 100, 50))
        self.pushButtonMul.setObjectName("pushButtonMul")
        self.pushButtonDiv = QtWidgets.QPushButton(Dialog)
        self.pushButtonDiv.setGeometry(QtCore.QRect(470, 300, 100, 50))
        self.pushButtonDiv.setObjectName("pushButtonDiv")
        self.labelResult = QtWidgets.QLabel(Dialog)
        self.labelResult.setGeometry(QtCore.QRect(0, 430, 600, 40))
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter first number:"))
        self.label_2.setText(_translate("Dialog", "Enter second number:"))
        self.pushButtonAdd.setText(_translate("Dialog", "+"))
        self.pushButtonSub.setText(_translate("Dialog", "-"))
        self.pushButtonMul.setText(_translate("Dialog", "*"))
        self.pushButtonDiv.setText(_translate("Dialog", "/"))
