# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/demoGroupCheckBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 650)
        font = QtGui.QFont()
        font.setPointSize(16)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 10, 58, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 221, 40))
        self.label_2.setObjectName("label_2")
        self.groupBoxIceCreams = QtWidgets.QGroupBox(Dialog)
        self.groupBoxIceCreams.setGeometry(QtCore.QRect(270, 60, 301, 231))
        self.groupBoxIceCreams.setObjectName("groupBoxIceCreams")
        self.checkBoxMintChocolateChips = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxMintChocolateChips.setGeometry(QtCore.QRect(20, 40, 261, 24))
        self.checkBoxMintChocolateChips.setObjectName("checkBoxMintChocolateChips")
        self.checkBoxCookieDough = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxCookieDough.setGeometry(QtCore.QRect(20, 90, 191, 24))
        self.checkBoxCookieDough.setObjectName("checkBoxCookieDough")
        self.checkBoxChocolateAlmond = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxChocolateAlmond.setGeometry(QtCore.QRect(20, 140, 231, 24))
        self.checkBoxChocolateAlmond.setObjectName("checkBoxChocolateAlmond")
        self.checkBoxRockyRoad = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxRockyRoad.setGeometry(QtCore.QRect(20, 190, 171, 24))
        self.checkBoxRockyRoad.setObjectName("checkBoxRockyRoad")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 350, 191, 40))
        self.label_3.setObjectName("label_3")
        self.groupBoxDrinks = QtWidgets.QGroupBox(Dialog)
        self.groupBoxDrinks.setEnabled(True)
        self.groupBoxDrinks.setGeometry(QtCore.QRect(270, 350, 231, 181))
        self.groupBoxDrinks.setObjectName("groupBoxDrinks")
        self.checkBoxCoffee = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxCoffee.setGeometry(QtCore.QRect(20, 40, 121, 24))
        self.checkBoxCoffee.setObjectName("checkBoxCoffee")
        self.checkBoxSoda = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxSoda.setGeometry(QtCore.QRect(20, 90, 101, 24))
        self.checkBoxSoda.setObjectName("checkBoxSoda")
        self.checkBoxTea = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxTea.setGeometry(QtCore.QRect(20, 140, 85, 24))
        self.checkBoxTea.setObjectName("checkBoxTea")
        self.labelAmount = QtWidgets.QLabel(Dialog)
        self.labelAmount.setGeometry(QtCore.QRect(0, 580, 700, 40))
        self.labelAmount.setText("")
        self.labelAmount.setObjectName("labelAmount")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Menu"))
        self.label_2.setText(_translate("Dialog", "Select your ice cream:"))
        self.groupBoxIceCreams.setTitle(_translate("Dialog", "Ice creams"))
        self.checkBoxMintChocolateChips.setText(_translate("Dialog", "Mint chocolate chips $4"))
        self.checkBoxCookieDough.setText(_translate("Dialog", "Cookie dough $2"))
        self.checkBoxChocolateAlmond.setText(_translate("Dialog", "Chocolate almond $3"))
        self.checkBoxRockyRoad.setText(_translate("Dialog", "Rocky road $5"))
        self.label_3.setText(_translate("Dialog", "Select your drink:"))
        self.groupBoxDrinks.setTitle(_translate("Dialog", "Drinks"))
        self.checkBoxCoffee.setText(_translate("Dialog", "Coffee $2"))
        self.checkBoxSoda.setText(_translate("Dialog", "Soda $3"))
        self.checkBoxTea.setText(_translate("Dialog", "Tea $1"))
