# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/reserveHotel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 800)
        font = QtGui.QFont()
        font.setPointSize(16)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 20, 231, 40))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 201, 40))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 340, 171, 40))
        self.label_3.setObjectName("label_3")
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setGeometry(QtCore.QRect(230, 80, 451, 251))
        self.calendarWidget.setObjectName("calendarWidget")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(230, 350, 71, 27))
        self.spinBox.setObjectName("spinBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 430, 121, 40))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(210, 440, 211, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButtonCalculateRoomRent = QtWidgets.QPushButton(Dialog)
        self.pushButtonCalculateRoomRent.setGeometry(QtCore.QRect(210, 510, 221, 40))
        self.pushButtonCalculateRoomRent.setObjectName("pushButtonCalculateRoomRent")
        self.labelEnterdInfo = QtWidgets.QLabel(Dialog)
        self.labelEnterdInfo.setGeometry(QtCore.QRect(0, 590, 700, 80))
        self.labelEnterdInfo.setText("")
        self.labelEnterdInfo.setObjectName("labelEnterdInfo")
        self.labelRoomRentInfo = QtWidgets.QLabel(Dialog)
        self.labelRoomRentInfo.setGeometry(QtCore.QRect(0, 710, 700, 80))
        self.labelRoomRentInfo.setText("")
        self.labelRoomRentInfo.setObjectName("labelRoomRentInfo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Hotel room reservation"))
        self.label_2.setText(_translate("Dialog", "Date of reservation:"))
        self.label_3.setText(_translate("Dialog", "Number of days:"))
        self.label_4.setText(_translate("Dialog", "Room type:"))
        self.comboBox.setItemText(0, _translate("Dialog", "Suite"))
        self.comboBox.setItemText(1, _translate("Dialog", "Super luxury"))
        self.comboBox.setItemText(2, _translate("Dialog", "Super deluxe"))
        self.comboBox.setItemText(3, _translate("Dialog", "Ordinary"))
        self.pushButtonCalculateRoomRent.setText(_translate("Dialog", "Calculate room rent"))
