# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/XML/addGenre_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addGenre_window(object):
    def setupUi(self, addGenre_window):
        addGenre_window.setObjectName("addGenre_window")
        addGenre_window.resize(890, 730)
        addGenre_window.setStyleSheet("QLabel#addCategory_label {\n"
"    background-color: green;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(addGenre_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(addGenre_window)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.genreName_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.genreName_label.setFont(font)
        self.genreName_label.setObjectName("genreName_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.genreName_label)
        self.genreName_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.genreName_lineEdit.setObjectName("genreName_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.genreName_lineEdit)
        self.addGenre_button = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addGenre_button.setFont(font)
        self.addGenre_button.setObjectName("addGenre_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.addGenre_button)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(addGenre_window)
        QtCore.QMetaObject.connectSlotsByName(addGenre_window)

    def retranslateUi(self, addGenre_window):
        _translate = QtCore.QCoreApplication.translate
        addGenre_window.setWindowTitle(_translate("addGenre_window", "Form"))
        self.genreName_label.setText(_translate("addGenre_window", "Name:"))
        self.addGenre_button.setText(_translate("addGenre_window", "Add genre"))
        self.label.setText(_translate("addGenre_window", "Add genre"))
