# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/XML/allGenres_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_allGenres_window(object):
    def setupUi(self, allGenres_window):
        allGenres_window.setObjectName("allGenres_window")
        allGenres_window.resize(890, 730)
        self.verticalLayout = QtWidgets.QVBoxLayout(allGenres_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(allGenres_window)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(allGenres_window)
        self.lineEdit.setPlaceholderText('Search genre for [Name]')
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.tableView = QtWidgets.QTableView(allGenres_window)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.setCursor(QtCore.Qt.PointingHandCursor)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(allGenres_window)
        QtCore.QMetaObject.connectSlotsByName(allGenres_window)

    def retranslateUi(self, allGenres_window):
        _translate = QtCore.QCoreApplication.translate
        allGenres_window.setWindowTitle(_translate("allGenres_window", "Form"))
        self.label.setText(_translate("allGenres_window", "All genres"))
