# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/XML/genre_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_genre_window(object):
    def setupUi(self, genre_window):
        genre_window.setObjectName("genre_window")
        genre_window.resize(890, 730)
        self.verticalLayout = QtWidgets.QVBoxLayout(genre_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label = QtWidgets.QLabel(genre_window)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.name_lineEdit = QtWidgets.QLineEdit(genre_window)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.name_lineEdit)
        self.label_2 = QtWidgets.QLabel(genre_window)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.editGenre_button = QtWidgets.QPushButton(genre_window)
        self.editGenre_button.setObjectName("editGenre_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.editGenre_button)
        self.deleteGenre_button = QtWidgets.QPushButton(genre_window)
        self.deleteGenre_button.setObjectName("deleteGenre_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.deleteGenre_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(genre_window)
        QtCore.QMetaObject.connectSlotsByName(genre_window)

    def retranslateUi(self, genre_window):
        _translate = QtCore.QCoreApplication.translate
        genre_window.setWindowTitle(_translate("genre_window", "Form"))
        self.label.setText(_translate("genre_window", "Edit genre"))
        self.label_2.setText(_translate("genre_window", "Name:"))
        self.editGenre_button.setText(_translate("genre_window", "Edit genre"))
        self.deleteGenre_button.setText(_translate("genre_window", "Delete genre"))
