# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/XML/settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.resize(890, 730)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(settings_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(settings_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.changeLanguage_button = QtWidgets.QPushButton(settings_window)
        self.changeLanguage_button.setObjectName("changeLanguage_button")
        self.gridLayout.addWidget(self.changeLanguage_button, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(settings_window)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.changeStyle_button = QtWidgets.QPushButton(settings_window)
        self.changeStyle_button.setObjectName("changeStyle_button")
        self.gridLayout.addWidget(self.changeStyle_button, 1, 2, 1, 1)
        self.style_comboBox = QtWidgets.QComboBox(settings_window)
        self.style_comboBox.setObjectName("style_comboBox")
        self.gridLayout.addWidget(self.style_comboBox, 1, 1, 1, 1)
        self.language_comboBox = QtWidgets.QComboBox(settings_window)
        self.language_comboBox.setObjectName("language_comboBox")
        self.gridLayout.addWidget(self.language_comboBox, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(settings_window)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.fontComboBox = QtWidgets.QFontComboBox(settings_window)
        self.fontComboBox.setObjectName("fontComboBox")
        self.gridLayout.addWidget(self.fontComboBox, 2, 1, 1, 1)
        self.changeFont_button = QtWidgets.QPushButton(settings_window)
        self.changeFont_button.setObjectName("changeFont_button")
        self.gridLayout.addWidget(self.changeFont_button, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(settings_window)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(settings_window)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "Form"))
        self.label.setText(_translate("settings_window", "Settings"))
        self.changeLanguage_button.setText(_translate("settings_window", "Change language"))
        self.label_2.setText(_translate("settings_window", "Style:"))
        self.changeStyle_button.setText(_translate("settings_window", "Change style"))
        self.label_3.setText(_translate("settings_window", "Language"))
        self.changeFont_button.setText(_translate("settings_window", "Change font"))
        self.label_4.setText(_translate("settings_window", "Font"))
