# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/XML/settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.resize(890, 730)
        self.gridLayout = QtWidgets.QGridLayout(settings_window)
        self.gridLayout.setObjectName("gridLayout")
        self.changeStyle_button = QtWidgets.QPushButton(settings_window)
        self.changeStyle_button.setObjectName("changeStyle_button")
        self.gridLayout.addWidget(self.changeStyle_button, 0, 2, 1, 1)
        self.changeFont_button = QtWidgets.QPushButton(settings_window)
        self.changeFont_button.setObjectName("changeFont_button")
        self.gridLayout.addWidget(self.changeFont_button, 1, 2, 1, 1)
        self.applicationStyle_label = QtWidgets.QLabel(settings_window)
        self.applicationStyle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.applicationStyle_label.setObjectName("applicationStyle_label")
        self.gridLayout.addWidget(self.applicationStyle_label, 0, 0, 1, 1)
        self.changeLanguage_button = QtWidgets.QPushButton(settings_window)
        self.changeLanguage_button.setObjectName("changeLanguage_button")
        self.gridLayout.addWidget(self.changeLanguage_button, 2, 2, 1, 1)
        self.applicationFont_comboBox = QtWidgets.QFontComboBox(settings_window)
        self.applicationFont_comboBox.setObjectName("applicationFont_comboBox")
        self.gridLayout.addWidget(self.applicationFont_comboBox, 1, 1, 1, 1)
        self.applicationLanguage_comboBox = QtWidgets.QComboBox(settings_window)
        self.applicationLanguage_comboBox.setObjectName("applicationLanguage_comboBox")
        self.gridLayout.addWidget(self.applicationLanguage_comboBox, 2, 1, 1, 1)
        self.applicationFont_label = QtWidgets.QLabel(settings_window)
        self.applicationFont_label.setAlignment(QtCore.Qt.AlignCenter)
        self.applicationFont_label.setObjectName("applicationFont_label")
        self.gridLayout.addWidget(self.applicationFont_label, 1, 0, 1, 1)
        self.applicationStyle_comboBox = QtWidgets.QComboBox(settings_window)
        self.applicationStyle_comboBox.setObjectName("applicationStyle_comboBox")
        self.gridLayout.addWidget(self.applicationStyle_comboBox, 0, 1, 1, 1)
        self.applicationLanguage_label = QtWidgets.QLabel(settings_window)
        self.applicationLanguage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.applicationLanguage_label.setObjectName("applicationLanguage_label")
        self.gridLayout.addWidget(self.applicationLanguage_label, 2, 0, 1, 1)

        self.retranslateUi(settings_window)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "Form"))
        self.changeStyle_button.setText(_translate("settings_window", "Change style"))
        self.changeFont_button.setText(_translate("settings_window", "Change font"))
        self.applicationStyle_label.setText(_translate("settings_window", "Style:"))
        self.changeLanguage_button.setText(_translate("settings_window", "Change language"))
        self.applicationFont_label.setText(_translate("settings_window", "Font:"))
        self.applicationLanguage_label.setText(_translate("settings_window", "Language:"))
